### ISSUE TITLE
Implement RegEnumKeyEx and RegEnumValue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [connor557/appstract#3]
```
Implement the following functions:
http://msdn.microsoft.com/en-us/library/ms724862(VS.85).aspx
http://msdn.microsoft.com/en-us/library/ms724865(VS.85).aspx
```

Original issue reported on code.google.com by `simon_al...@hotmail.com` on 12 May 2009 at 7:34

**Comment by connor557** [comment]
Need to do more research on this. If anybody finds a solution, feel free to submit a pull request.
